### ISSUE TITLE
MOAR CATS

### ISSUE THREAD

**Issue by micahwalter** [metmuseum-medialab/Met_Chrome_Extension#1]
This is my newest favorite chrome extension. 

Really, it rocks! I open new tabs all day just to see a new cat.

There are currently only 40 cats. They appear to each be hard coded into 40 different html files.

I'd like the extension to pull in random cats from the Met's collection database, perhaps through an API. 

This would mean MOAR CATS!

**Comment by jedahan** [comment]
Cool idea!

I don't know how well extensions deal with cross-site requests, but it seems http://scrapi.org/search/cat could return a bunch of cat urls...

``` bash
curl http://scrapi.org/search/cat | jq '.collection.items[].image_thumb' | sed -e 's/web-thumb/original/'
```

or in javascript, maybe (untested)

``` js
function reqListener() {
  var search = JSON.parse(this.responseText)
  var items = search.collection.items
  var item = items[Math.floor(Math.random(items.length))]
  var url = item.image_thumb.replace("web-thumb","original")
  console.log(url)
}

var req = new XMLHttpRequest();
req.onload = reqListener
req.open("get", "http://scrapi.org/search/cat", true);
req.send();
```
